version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-transform-modules-commonjs"
    versions:
    - 7.12.1
  - dependency-name: jasmine
    versions:
    - 3.6.3
  - dependency-name: "@babel/plugin-external-helpers"
    versions:
    - 7.12.1
